---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Senthil Maruthaiappan, Software Professtional"
keywords:    "Senthil, Maruthaiappan, vallalarspace, database testing, .net ui automation, cloud service, platform service, Delphi/Pascal, Object C, C++, .Net, Java, Netflix OSS, Spring Cloud, CI/CD, continuous Delivery, continuous integreation, TDD, BDD, Cucumber"
description: "A single-page about me"
source_link: "https://github.com/senips"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-63842133-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
